import { z } from "zod";

export const ScopeSchema = z.object({
  teamId: z.string().min(1).max(100),
  projectId: z.string().min(1).max(100),
});

export const EvidenceSchema = z.object({
  kind: z.enum(["ticket", "test", "review", "commit"]),
  reference: z.string().min(1).max(500),
  summary: z.string().min(1).max(2000),
});

export const HarnessChangeSchema = z.object({
  instructions: z.array(z.string().min(1).max(2000)).max(10),
  verificationSteps: z.array(z.string().min(1).max(500)).max(10),
  // Names from a fixed registered-tool allowlist, not executable code.
  suggestedTools: z.array(z.string().min(1).max(100)).max(10),
});

export const CandidateInputSchema = z.object({
  title: z.string().min(1).max(160),
  lesson: z.string().min(1).max(4000),
  authorId: z.string().min(1).max(100),
  appliesTo: z.array(z.string().min(1).max(100)).max(20),
  evidence: z.array(EvidenceSchema).min(1).max(20),
  proposedChange: HarnessChangeSchema,
}).strict();

export const LessonSchema = CandidateInputSchema.extend({
  id: z.string(),
  teamId: z.string(),
  projectId: z.string(),
  status: z.enum(["candidate", "published", "rejected", "superseded"]),
  version: z.number().int().positive(),
  origin: z.enum(["demo", "submitted"]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export const MemorySnapshotSchema = z.object({
  scope: ScopeSchema,
  lessons: z.array(LessonSchema),
  fetchedAt: z.string().datetime(),
  // The harness version these lessons come from; absent from older servers.
  harnessVersion: z.number().int().min(0).optional(),
});

export const EvaluateRequestSchema = z.object({
  expectedVersion: z.number().int().positive(),
}).strict();

export const ENGINEER_ID_HEADER = "x-engineer-id";

const ENGINEER_ID_PATTERN = /^[\w.-]{1,100}$/;

export function engineerIdFromHeader(value: string | string[] | undefined): string {
  const raw = Array.isArray(value) ? value[0] : value;
  if (!raw) return "unspecified";
  const trimmed = raw.trim();
  return ENGINEER_ID_PATTERN.test(trimmed) ? trimmed : "unspecified";
}

export type Scope = z.infer<typeof ScopeSchema>;
export type CandidateInput = z.infer<typeof CandidateInputSchema>;
export type Lesson = z.infer<typeof LessonSchema>;
export type MemorySnapshot = z.infer<typeof MemorySnapshotSchema>;

// Native tickets use the implemented, validated record shape.
export type { TicketRecord as Ticket } from "./tickets.js";

// Future agent-event ingestion contract. No /v1/agent-changes route is registered.
export interface AgentChangeInput {
  eventId: string; // Stable across retries, for scoped idempotency.
  ticketKey: string;
  agentId: string;
  sessionId: string;
  kind: "observation" | "triage-proposal" | "verification-result" | "lesson-candidate" | "memory-applied";
  summary: string;
  observedAt: string;
  before?: Record<string, unknown>;
  after?: Record<string, unknown>;
  evidence: z.infer<typeof EvidenceSchema>[];
  lessonId?: string;
}

export interface AgentChange extends AgentChangeInput, Scope {
  id: string;
  engineerId: string; // Assigned by the service from authenticated identity.
  recordedAt: string;
}

export type EvaluateRequest = z.infer<typeof EvaluateRequestSchema>;

export interface LessonVersionRef {
  id: string;
  version: number;
}

export interface EvaluationCaseResult {
  caseId: string;
  ticketKey: string;
  applied: boolean;
  component: string | null;
  componentCorrect: boolean;
  checksCovered: number;
  checksTotal: number;
}

export interface EvaluationScores {
  suiteVersion: string;
  evaluatorVersion: string;
  baselineScore: number;
  candidateScore: number;
  regressions: string[];
  decision: "publish" | "reject" | "needs-review";
  cases: EvaluationCaseResult[];
}

export interface EvaluationResult extends EvaluationScores {
  id: string;
  teamId: string;
  projectId: string;
  lessonId: string;
  candidateVersion: number;
  createdAt: string;
}

export interface AuditEvent {
  id: string;
  teamId: string;
  projectId: string;
  kind: "lesson.proposed" | "lesson.evaluated" | "lesson.published" | "lesson.rejected" | "memory.consumed"
    | "harness.updated" | "harness.rollback";
  lessonId: string | null;
  lessonVersion: number | null;
  actorId: string;
  at: string;
  summary: string;
  consumed?: LessonVersionRef[];
  harnessVersion?: number;
}

// Harness versions are implemented in ./harness.ts. A version selects published lessons;
// agents receive them as context or generated skills. It never grants tools or access.

export function renderMemory(snapshot: MemorySnapshot): string {
  const lines = [
    "# Shared team memory",
    "",
    "> Generated cache. Submit changes as lesson candidates; do not edit this file.",
    `> Scope: ${snapshot.scope.teamId} / ${snapshot.scope.projectId}`,
    ...(snapshot.harnessVersion === undefined ? [] : [`> Harness version: v${snapshot.harnessVersion}`]),
    `> Last fetched: ${snapshot.fetchedAt}`,
    "",
  ];
  const published = snapshot.lessons.filter((lesson) => lesson.status === "published");
  if (published.length === 0) lines.push("No published lessons are available.");
  for (const lesson of published) {
    lines.push(
      `## ${lesson.title}`,
      "",
      `ID: ${lesson.id} · version ${lesson.version} · origin: ${lesson.origin}`,
      `Applies to: ${lesson.appliesTo.join(", ") || "project-wide"}`,
      "",
      lesson.lesson,
      "",
      ...lesson.evidence.map((e) => `- Evidence (${e.kind}): ${e.reference} — ${e.summary}`),
      "",
    );
  }
  return `${lines.join("\n")}\n`;
}
