import { z } from "zod";

export const ScopeSchema = z.object({
  teamId: z.string().min(1).max(100),
  projectId: z.string().min(1).max(100),
});

export const EvidenceSchema = z.object({
  kind: z.enum(["ticket", "test", "review", "commit"]),
  reference: z.string().min(1).max(500),
  summary: z.string().min(1).max(2000),
});

export const HarnessChangeSchema = z.object({
  instructions: z.array(z.string().min(1).max(2000)).max(10),
  verificationSteps: z.array(z.string().min(1).max(500)).max(10),
  // Names from a fixed registered-tool allowlist, not executable code.
  suggestedTools: z.array(z.string().min(1).max(100)).max(10),
});

export const CandidateInputSchema = z.object({
  title: z.string().min(1).max(160),
  lesson: z.string().min(1).max(4000),
  authorId: z.string().min(1).max(100),
  appliesTo: z.array(z.string().min(1).max(100)).max(20),
  evidence: z.array(EvidenceSchema).min(1).max(20),
  proposedChange: HarnessChangeSchema,
}).strict();

export const LessonSchema = CandidateInputSchema.extend({
  id: z.string(),
  teamId: z.string(),
  projectId: z.string(),
  status: z.enum(["candidate", "published", "rejected", "superseded"]),
  version: z.number().int().positive(),
  origin: z.enum(["demo", "submitted"]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export const MemorySnapshotSchema = z.object({
  scope: ScopeSchema,
  lessons: z.array(LessonSchema),
  fetchedAt: z.string().datetime(),
});

export type Scope = z.infer<typeof ScopeSchema>;
export type CandidateInput = z.infer<typeof CandidateInputSchema>;
export type Lesson = z.infer<typeof LessonSchema>;
export type MemorySnapshot = z.infer<typeof MemorySnapshotSchema>;

// Planned ticket/log contracts for frontend/, the API, and Pi. Routes/storage are not implemented.
export interface Ticket extends Scope {
  key: string;
  summary: string;
  description: string;
  component: string | null;
  acceptanceCriteria: string[];
  updatedAt: string;
}

export interface AgentChangeInput {
  eventId: string; // Stable across retries, for scoped idempotency.
  ticketKey: string;
  agentId: string;
  sessionId: string;
  kind: "observation" | "triage-proposal" | "verification-result" | "lesson-candidate" | "memory-applied";
  summary: string;
  observedAt: string;
  before?: Record<string, unknown>;
  after?: Record<string, unknown>;
  evidence: z.infer<typeof EvidenceSchema>[];
  lessonId?: string;
}

export interface AgentChange extends AgentChangeInput, Scope {
  id: string;
  engineerId: string; // Assigned by the service from authenticated identity.
  recordedAt: string;
}

// Planned storage contracts. No promotion endpoint exists in this starter.
export interface EvaluationResult {
  id: string;
  lessonId: string;
  candidateVersion: number;
  suiteVersion: string;
  evaluatorVersion: string;
  baselineScore: number;
  candidateScore: number;
  regressions: string[];
  decision: "publish" | "reject" | "needs-review";
}

export interface HarnessVersion extends Scope {
  id: string;
  parentVersionId: string | null;
  lessonIds: string[];
  evaluationIds: string[];
  change: z.infer<typeof HarnessChangeSchema>;
  status: "candidate" | "active" | "retired";
}

export function renderMemory(snapshot: MemorySnapshot): string {
  const lines = [
    "# Shared team memory",
    "",
    "> Generated cache. Submit changes as lesson candidates; do not edit this file.",
    `> Scope: ${snapshot.scope.teamId} / ${snapshot.scope.projectId}`,
    `> Last fetched: ${snapshot.fetchedAt}`,
    "",
  ];
  const published = snapshot.lessons.filter((lesson) => lesson.status === "published");
  if (published.length === 0) lines.push("No published lessons are available.");
  for (const lesson of published) {
    lines.push(
      `## ${lesson.title}`,
      "",
      `ID: ${lesson.id} · version ${lesson.version} · origin: ${lesson.origin}`,
      `Applies to: ${lesson.appliesTo.join(", ") || "project-wide"}`,
      "",
      lesson.lesson,
      "",
      ...lesson.evidence.map((e) => `- Evidence (${e.kind}): ${e.reference} — ${e.summary}`),
      "",
    );
  }
  return `${lines.join("\n")}\n`;
}
